# templates/aws-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretKey | b64enc }}
